plugins {
    id 'com.android.application'
}

android {
    namespace "arri.lsposed.notifhider"
    compileSdk 34

    defaultConfig {
        applicationId "arri.lsposed.notifhider"
        minSdk 31
        targetSdk 34
        versionCode 1
        versionName "0.1"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
}
